### ISSUE TITLE
Servant Handler

### ISSUE THREAD

**Issue by Dgwrigh58** [Torwent/wasp-free#14]
https://github.com/Torwent/wasp-free/blob/6b3e891df0952767fee70c3cef1b5c722337ceda/larder_builder.simba#L224

Does this have to be

`Result := Chat.ClickOption('Un note', BioHash);`

**Comment by Torwent** [comment]
No because when you are using a servant you don't usually have the planks on you, you have them in your bank and ask the servant to fetch them for you. I could look into adding unnote support but it's working as it should right now
